name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install werkzeug==2.2.3

      - name: Verify Installed Versions
        run: |
          python -c "import werkzeug; print('Werkzeug Version:', werkzeug.__version__)"
          python -c "import flask; print('Flask Version:', flask.__version__)"

      - name: Run tests
        run: python -m unittest discover
